services:
  onlyoffice-documentserver:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
      #dockerfile: Dockerfile.debian
    container_name: onlyoffice-documentserver
    ports:
      - '80:80'
